<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Authors>xfunc</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/xfunc/formidable</RepositoryUrl>
        <PackageProjectUrl>https://github.com/xfunc/formidable</PackageProjectUrl>
        <MinVerTagPrefix>v</MinVerTagPrefix>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
    </ItemGroup>
</Project>
